server:
  port: 8080
spring:
  output.ansi.enabled: ALWAYS
  datasource:
    url: "jdbc:postgresql://172.17.0.1:5435/tasksBase"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    database: POSTGRESQL
    hibernate:
      dialect: org.hibernate.dialect.PostgresSQLDialect
      default-schema: tasks_schema
      ddl-auto: none
    defer-datasource-initialization: true
  show-sql: true

api:
  host: "http://172.17.0.1"
  serverPort: 8080
  gatewayPort: 8765
  urlApiTasks: "/tasks"
  urlApiMessages: "/messages"
  urlApiUsers: "/users"
  urlApiAdds: "/adds"
  pathFileStorage: "FILES/"



  
